Pull file-level analysis out into its own object.
google/wireit pull request #194
Opened 2022-05-06 18:44 UTC by rictic

This way we can generate fewer duplicate diagnostics and walk the package.json file's large scale structure only once rather than once for each script.

Part of working towards IDE support, because what we _really_ want to do is say "give me all the diagnostics in these open files" or perhaps "starting from these files, give me all reachable diagnostics". However I think even just by itself this will be useful for deduplicating diagnostics.

2022-05-06 21:37 UTC, rictic commented
Ah, got a windows path issue in an error message, will fix

2022-05-06 21:39 UTC, rictic commented
Ok, I think this is ready for review!

2022-05-06 22:13 UTC, aomarks commented
> This way we can generate fewer duplicate diagnostics and walk the package.json file's large scale structure only once rather than once for each script.

How did we generate duplicate diagnostics before? Wasn't everything always done on a per-script basis, and we only looked at each script once?

2022-05-07 00:56 UTC, rictic commented
Well the problem was threefold. First, some problems were file level, so every dependency would encounter it the same, second, execution problems were repeated for every dependent, and third there was a race condition in the caching package json reader such that even with some deduplication added we would still see dupes because caching a file was racy

2022-05-09 18:53 UTC, aomarks commented
> Well the problem was threefold. First, some problems were file level, so for every script that we would attempt to run in that file we would generate the same failure. See the new test `"we don't produce a duplicate error when there's multiple deps into the same invalid file"`. That's a fairly rare case but it's there.
> 
> Second, failures during execution were logged for every dependent. I noticed this when hacking on wireit, which got me started down this path. Add a TypeScript error and run `npm test` and you'll see a log about how the build script exited with code 1 for each test script.
> 
> And third, there was a race condition in the caching package json reader such that even after adding deduplication logic we would still get dupes because caching a file was racy, and in a lot of situations we've probably been reading and parsing the same file many times. That's a very easy mistake to make, so I added a little async cache class with a safe API.

Got it, thanks for explanation! Great improvements.

2022-05-09 18:53 UTC, aomarks requested changes
Looks great! Just a few questions/comments.

2022-05-09 18:53 UTC, aomarks commented on src/util/package-json-reader.ts
>  export interface JsonFile {
Should `JsonFile` be in `ast.ts`? It's not used by `package-json-reader.ts` anymore.

2022-05-09 18:53 UTC, aomarks commented on src/analyzer.ts
> +  async #readPackageJson(packageDir: string): Promise<Result<PackageJson>> {
Maybe just inline this, since it's only used in one place and is trivial and already readable.

2022-05-09 18:53 UTC, aomarks commented on src/analyzer.ts
>   * Throw an error if it was an object literal ({...}), assuming it was parsed
Can be another PR, but just noticed a bunch of these functions now have incorrect jsdoc, since they don't throw anymore.

2022-05-09 18:53 UTC, aomarks commented on src/event.ts
> +interface ScriptlessError {
Isn't there always at least a package json path? Why can't `PackageJsonPathError` and `InvalidConfigSyntax` have `extends ErrorBase<PackageReference>>`?

2022-05-09 18:53 UTC, aomarks commented on src/logging/default-logger.ts
> +        const prefix = this.#getPrefix(event.script);
Related to other comment, not sure I understand why we wouldn't always have a `PackageReference` at least.

2022-05-09 21:29 UTC, merged